# Generated by Django 6.0 on 2025-12-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
